# Generated by Django 5.2.1 on 2025-05-09 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('inn', models.CharField(max_length=12, verbose_name='ИНН')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=255, verbose_name='Имя')),
                ('lastname', models.CharField(max_length=255, verbose_name='Фамилия')),
                ('middlename', models.CharField(blank=True, max_length=255, verbose_name='Отчество')),
                ('position', models.CharField(max_length=255, verbose_name='Должность')),
                ('snils', models.CharField(max_length=11, verbose_name='СНИЛС')),
                ('birth', models.DateField(verbose_name='Дата рождения')),
                ('serial', models.CharField(max_length=20, verbose_name='Серия паспорта')),
                ('number', models.CharField(max_length=20, verbose_name='Номер паспорта')),
                ('by', models.CharField(max_length=255, verbose_name='Кем выдан')),
                ('when', models.DateField(verbose_name='Дата выдачи')),
                ('reg_address', models.CharField(max_length=255, verbose_name='Адрес регистрации')),
                ('home_address', models.CharField(max_length=255, verbose_name='Адрес проживания')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
            ],
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название программы')),
                ('system_id', models.CharField(max_length=12, verbose_name='Системное ID')),
            ],
        ),
    ]
