# Generated by Django 5.2.1 on 2025-05-09 07:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='by',
            field=models.CharField(blank=True, max_length=255, verbose_name='Кем выдан'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='home_address',
            field=models.CharField(blank=True, max_length=255, verbose_name='Адрес проживания'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='number',
            field=models.CharField(blank=True, max_length=20, verbose_name='Номер паспорта'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='reg_address',
            field=models.CharField(blank=True, max_length=255, verbose_name='Адрес регистрации'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='serial',
            field=models.CharField(blank=True, max_length=20, verbose_name='Серия паспорта'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='snils',
            field=models.CharField(blank=True, max_length=11, verbose_name='СНИЛС'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='when',
            field=models.DateField(blank=True, verbose_name='Дата выдачи'),
        ),
        migrations.CreateModel(
            name='Decree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, verbose_name='Дата')),
                ('number', models.CharField(max_length=255, verbose_name='Номер')),
                ('main', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='main_person', to='ot.employee', verbose_name='Председатель')),
                ('second', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='second_person', to='ot.employee', verbose_name='Второй')),
                ('third', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='third_person', to='ot.employee', verbose_name='Третий')),
            ],
        ),
    ]
