# Generated by Django 5.2.1 on 2025-05-09 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ot', '0002_alter_employee_by_alter_employee_home_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='short_title',
            field=models.CharField(default='', max_length=255, verbose_name='Сокращенное название'),
            preserve_default=False,
        ),
    ]
