# Generated by Django 5.2.1 on 2025-05-09 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ot', '0003_company_short_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='short_title',
            field=models.CharField(default='ПП', max_length=10, verbose_name='Краткое название программы'),
            preserve_default=False,
        ),
    ]
